apiVersion: apps/v1
kind: Deployment
metadata:
    name: -deploy
spec:
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: main
            image: main:1.0.0
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
